### ISSUE TITLE
Los textos del menú superior centrados

### ISSUE THREAD

**Issue by yeifabgm** [Tacma/Veur-landing#12]
Los elementos del menú deben ir centrados verticamente
![nav-center](https://user-images.githubusercontent.com/7909817/30432125-55c73d98-9926-11e7-9da3-309bd862d0dc.png)

**Recomencación:**
Use el nav de bootstrap, ejemplos:
https://codepen.io/bootstrapped/pen/KwYGwq

**Comment by yeifabgm** [comment]
@brodriguezs, por favor ayudele al muchacho

**Comment by Tacma** [comment]
cambios realizados en commit #10 "Centrar navbar" @yeifabgm por faor revisar :D gracias

**Comment by yeifabgm** [comment]
Perfecto!
