### ISSUE TITLE
Títulos de los slider del Carousel

### ISSUE THREAD

**Issue by yeifabgm** [Tacma/Veur-landing#4]
Los titulos del carousel deben ir en HTML. Es mejor para el SEO, ya que es mas texto que el buscador puede indexar.
En el siguiente enlace se puede ver un ejemplo de como integrar con el texto:
https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_carousel2&stacked=h

**Comment by Tacma** [comment]
Esto se cambio se agrego en el commit #7 cambios banner

**Comment by yeifabgm** [comment]
Ok, gracias!
